# Generated by Django 3.0.2 on 2020-03-13 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=13)),
                ('email', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('usertype', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=20)),
                ('verified', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'login',
            },
        ),
        migrations.CreateModel(
            name='sellers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=13)),
                ('email', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('zipcode', models.CharField(max_length=6)),
            ],
            options={
                'db_table': 'sellers',
            },
        ),
    ]
