# Generated by Django 3.0.2 on 2020-03-16 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_auto_20200316_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='login',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sellers',
            name='email',
            field=models.CharField(max_length=50),
        ),
    ]
