# Generated by Django 3.0.2 on 2020-03-17 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_auto_20200316_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='customerlogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerid', models.IntegerField()),
            ],
            options={
                'db_table': 'customerlogin',
            },
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('idealfor', models.CharField(max_length=20)),
                ('stock', models.IntegerField()),
                ('sellerId', models.IntegerField()),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='sellerlogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sellerid', models.IntegerField()),
            ],
            options={
                'db_table': 'sellerlogin',
            },
        ),
    ]
