# Generated by Django 3.0.2 on 2020-03-18 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_customerlogin_products_sellerlogin'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.CharField(default='image', max_length=100),
            preserve_default=False,
        ),
    ]
