# Generated by Django 3.0.2 on 2020-03-18 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_products_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=50)),
                ('cdate', models.DateField()),
                ('ctime', models.TimeField()),
                ('camount', models.IntegerField()),
                ('caddress', models.CharField(max_length=500)),
                ('cstatus', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
    ]
