# Generated by Django 3.0.2 on 2020-03-18 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='czipcode',
            field=models.CharField(default='0', max_length=20),
            preserve_default=False,
        ),
    ]
