# Generated by Django 3.0.2 on 2020-03-18 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_orders_czipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='cdate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='ctime',
            field=models.TimeField(null=True),
        ),
    ]
