# Generated by Django 3.0.2 on 2020-03-18 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0009_auto_20200318_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='zipcode',
            field=models.CharField(default='0', max_length=20),
            preserve_default=False,
        ),
    ]
