# Generated by Django 3.0.2 on 2020-03-19 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0010_products_zipcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='czipcode',
        ),
        migrations.AddField(
            model_name='orders',
            name='csellerid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
