# Generated by Django 3.0.2 on 2020-03-19 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0011_auto_20200319_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='cards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cardnumber', models.CharField(max_length=19)),
                ('cvv', models.IntegerField()),
                ('expdate', models.CharField(max_length=7)),
            ],
            options={
                'db_table': 'cards',
            },
        ),
        migrations.AddField(
            model_name='orders',
            name='cproductid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
