# Generated by Django 2.2.6 on 2020-03-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0012_auto_20200319_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
