# Generated by Django 2.2.6 on 2020-03-19 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0013_auto_20200319_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='cid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
