# Generated by Django 2.2.6 on 2020-03-19 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0014_orders_cid'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='citemname',
            field=models.CharField(default='perfume', max_length=20),
            preserve_default=False,
        ),
    ]
