# Generated by Django 2.2.6 on 2020-03-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0015_orders_citemname'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='cimage',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
